### ISSUE TITLE
Arrays of hashes are not recursively diff'd

### ISSUE THREAD

**Issue by flyinbutrs** [Blargel/easy_diff#11]
So, I love this tool. But, I'm trying to diff some rather complicated JSON documents, and everything goes swimmingly until an array contains hashes. My preferred behavior would be to recursively diff each hash in the array. I'm looking at the code, and may attempt this myself, but I'm wondering if you've already tried and hit issues.

**Comment by Blargel** [comment]
Yes, I have tried it and it's not the best idea unless you want to implement some fairly complicated logic to determine which hash should be compared to which. For example, let's pretend your data looks like this.

`[ { :a => 1, :b => 2 }, { :b => 2, :c => 3 }, { :b => 2, :c => 4 } ]`

And now you want to compare the data to this:

`[ { :b => 2, :c => 5 }, { :a => 1, :b => 2 } ]`

So, what's the expected output? The first element of the first array is obviously the same as the second element of the array, so we can't just compare matching indexes. I believe that in order to properly do this, one would need to implement a way to represent differing array positions, which I currently do not have an idea on how to represent in the removed/added hashes that are returned.

**Comment by flyinbutrs** [comment]
Hmmm....  that makes sense. For my particular case, taking the array hashes in order would work fine 95% of the time, but I definitely see your point. I may just put a wrapper around it for my use case, or possibly (shudder) figure out how to restructure the data so it's purely hash.

**Comment by flyinbutrs** [comment]
I took a shot at it... #12

**Comment by Blargel** [comment]
Pull request #12 breaks merge/unmerge and is not a generalized solution for recursing through arrays. I'm going to close this for now since I don't plan on implementing an alternate solution any time soon. Any generalized solution for this will almost definitely change the structure of diffs and possibly break things for people who use this gem. (Did I mention I'm completely baffled why this gem is so popular?)
