### ISSUE TITLE
Diff breaks for hashes within arrays

### ISSUE THREAD

**Issue by siepet** [Blargel/easy_diff#8]
Hi, I've came across a problem with easy_diff that breaks, but I'm not sure why, because for some nested hashes it works fine, here is the gist that demonstrates the weird behaviour:

https://gist.github.com/anonymous/f2995ef213e4c8f8f54c

With given hashes, the output for removed should be an empty hash, but instead it gives whole hash.
I think it's a bug, unless it's not then i would like to know what exactly is causing this.

Easy_diff 0.0.6
ruby -v:
```ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]```

**Comment by Blargel** [comment]
The odd behavior appears to be caused by putting hashes inside of arrays. I have an idea why this is broken, but I don't have a solid answer for it yet.

**Comment by Blargel** [comment]
Okay, so the current behavior is _technically_ correct but perhaps not what one would expect at first. The problem lies in the fact that there's no way for the comparison to currently know, for example, which hash should be compared to which if there are multiple hashes in an array. Blindly comparing the first hash with the first (and so forth) is error-prone and not an option. As such, if the entire hash is not exactly the same, it is assumed that the entire hash is different.

On the plus side, if you use merge or unmerge with these resulting added/removed hashes, it should still work correctly though.

**Comment by Blargel** [comment]
There is no way I can see that can make the diff how you expect it without also breaking merge/unmerge.
